export const TOOL_CAPABILITIES = Object.freeze({
  gmail: {
    name: 'gmail',
    consumes: ['person_reference', 'recipient', 'subject_text', 'body_text', 'text_note'],
    produces: ['email_draft', 'draft_review'],
    actions: ['open', 'draft', 'review', 'send'],
    risk_level: 'high',
    requires_confirmation: true,
    ui_surface: 'mixed',
    repairable_fields: ['recipient', 'subject', 'body'],
  },
  telegram: {
    name: 'telegram',
    consumes: ['person_reference', 'recipient', 'message_text', 'media_link', 'video_link'],
    produces: ['telegram_draft', 'message_delivery'],
    actions: ['open', 'draft', 'send'],
    risk_level: 'high',
    requires_confirmation: true,
    ui_surface: 'mixed',
    repairable_fields: ['recipient', 'message', 'attachment'],
  },
  timer: {
    name: 'timer',
    consumes: ['duration', 'label_text'],
    produces: ['timer_state'],
    actions: ['set', 'cancel'],
    risk_level: 'low',
    requires_confirmation: false,
    ui_surface: 'panel',
    repairable_fields: ['duration', 'label'],
  },
  notes: {
    name: 'notes',
    consumes: ['body_text', 'query_text'],
    produces: ['text_note', 'note_match'],
    actions: ['capture', 'find', 'delete'],
    risk_level: 'medium',
    requires_confirmation: false,
    ui_surface: 'mixed',
    repairable_fields: ['content', 'target_note'],
  },
  youtube: {
    name: 'youtube',
    consumes: ['query_text'],
    produces: ['video_link', 'title'],
    actions: ['search', 'open'],
    risk_level: 'low',
    requires_confirmation: false,
    ui_surface: 'panel',
    repairable_fields: ['query'],
  },
  weather: {
    name: 'weather',
    consumes: ['location', 'date_time'],
    produces: ['forecast', 'condition'],
    actions: ['lookup'],
    risk_level: 'none',
    requires_confirmation: false,
    ui_surface: 'panel',
    repairable_fields: ['location', 'date_time'],
  },
  camera: {
    name: 'camera',
    consumes: ['camera_mode', 'alert_rule'],
    produces: ['live_feed_state', 'image_frame'],
    actions: ['start_live', 'stop_live', 'monitor'],
    risk_level: 'high',
    requires_confirmation: true,
    ui_surface: 'mixed',
    repairable_fields: ['mode', 'alert_rule'],
  },
  arcade: {
    name: 'arcade',
    consumes: ['tool_name', 'toolkit_name', 'input_data', 'user_intent'],
    produces: ['tool_result', 'auth_link', 'missing_input_request'],
    actions: ['execute', 'list', 'authorize'],
    risk_level: 'mixed',
    requires_confirmation: true,
    ui_surface: 'mixed',
    repairable_fields: ['tool_name', 'inputs'],
  },
});

export function getToolCapability(toolName) {
  return TOOL_CAPABILITIES[toolName] || null;
}
